name: Generate Arcade Games

on:
  schedule:
    - cron: "0 */12 * * *" # every 12 hours
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Arcade Games
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}
          games: 'pacman,galaga'
          
      - name: Commit & Push generated files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update Arcade Games"
          file_pattern: "dist/*.svg"
